name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller
          if (Test-Path requirements.txt) { python -m pip install -r requirements.txt }

      - name: Build executable with PyInstaller
        shell: pwsh
        run: |
          python -m PyInstaller --onefile --windowed auto.py

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: auto-executable
          path: dist/auto.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: dist/autopaino.exe

      - name: Clean build directories
        shell: pwsh
        run: |
          Remove-Item -Recurse -Force build, dist, auto.spec -ErrorAction SilentlyContinue

