name: Build and Release

on:
  push:
    tags:
      - 'v*'       # 当推送以 'v' 开头的标签时触发
  workflow_dispatch:    # 允许手动触发工作流

permissions:
  contents: write       # 允许工作流写入仓库内容，如创建 Release

jobs:
  build-and-release:
    runs-on: windows-latest    # 使用 Windows 环境以生成 .exe 文件

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'   # 根据项目需求选择 Python 版本

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller
          if (Test-Path requirements.txt) { python -m pip install -r requirements.txt }

      - name: Build executable with PyInstaller
        shell: pwsh
        run: |
          python -m PyInstaller --onefile --windowed auto.py

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v3
        with:
          name: auto-executable
          path: dist/auto.exe

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1.15.0
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: dist/auto.exe